-- Consulta 01: Identificação de funcionários, cargos e departamentos com salário > 5000
SELECT 
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    DEPARTMENT_NAME,
    JOB_TITLE
FROM HR.EMPLOYEES
LEFT JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
LEFT JOIN HR.JOBS ON HR.EMPLOYEES.JOB_ID = HR.JOBS.JOB_ID
WHERE SALARY > 5000;


-- Consulta 02: Extração de Salários e Localização Completa (Cidades, Países e Regiões)
SELECT 
    FIRST_NAME, 
    LAST_NAME, 
    SALARY,
    CITY,
    STATE_PROVINCE,
    COUNTRY_NAME,
    REGION_NAME
FROM HR.EMPLOYEES
LEFT JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS ON HR.DEPARTMENTS.LOCATION_ID = HR.LOCATIONS.LOCATION_ID
LEFT JOIN HR.COUNTRIES ON HR.LOCATIONS.COUNTRY_ID = HR.COUNTRIES.COUNTRY_ID
LEFT JOIN HR.REGIONS ON HR.COUNTRIES.REGION_ID = HR.REGIONS.REGION_ID
WHERE REGION_NAME IS NOT NULL;
