SELECT 
   FIRST_NAME, 
   LAST_NAME, 
   SALARY, 
   CITY, 
   STATE_PROVINCE, 
   COUNTRY_NAME, 
   REGION_NAME
FROM HR.EMPLOYEES
LEFT JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS ON HR.DEPARTMENTS.LOCATION_ID = HR.LOCATIONS.LOCATION_ID
LEFT JOIN HR.COUNTRIES ON HR.LOCATIONS.COUNTRY_ID = HR.COUNTRIES.COUNTRY_ID
LEFT JOIN HR.REGIONS ON HR.COUNTRIES.REGION_ID = HR.REGIONS.REGION_ID
WHERE REGION_NAME IS NOT NULL;