SELECT 
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    DEPARTMENT_NAME,
    JOB_TITLE
FROM HR.EMPLOYEES
LEFT JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
LEFT JOIN HR.JOBS ON HR.EMPLOYEES.JOB_ID = HR.JOBS.JOB_ID
WHERE SALARY > 0;